import Bar from "@/components/bar/Bar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import DesktopProvider from "@/components/providers/DesktopProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DesktopProvider>
          <div className="flex min-h-screen flex-col bg-[url(/images/wallpaper.jpg)] bg-cover bg-no-repeat">
            {children}
            <Bar />
          </div>
        </DesktopProvider>
      </body>
    </html>
  );
}
